/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDRESS		0x40023800UL

#define RCC_AHB1ENR_OFFSET		0x30UL
#define RCC_AHB1ENR				(RCC_BASE_ADDRESS + RCC_AHB1ENR_OFFSET)

#define RCC_CFGR_OFFSET			0x08UL
#define RCC_CFGR				(RCC_BASE_ADDRESS + RCC_CFGR_OFFSET)

#define GPIOA_ADDRESS			0x40020000UL
#define GPIOx_MODER_OFFSET		0x00UL
#define GPIOA_MODER				(GPIOA_ADDRESS + GPIOx_MODER_OFFSET)

#define GPIOx_AFHR_OFFSET		0x24UL
#define GPIOA_AFHR				(GPIOA_ADDRESS + GPIOx_AFHR_OFFSET)

int main(void)
{

	uint32_t *pRCC_AHB1ENR	= (uint32_t*)RCC_AHB1ENR;

	uint32_t *pRCC_CFGR		= (uint32_t*)RCC_CFGR;
	uint32_t *pGPIOA_MODER	= (uint32_t*)GPIOA_MODER;

	//1. Enable AHB1 clock
	*pRCC_AHB1ENR |=  1;

	//2. Select clock source for MCO1 is HSI
	*pRCC_CFGR &= ~(3 << 21);
	//	 Config MCO1 prescaler is 2
	*pRCC_CFGR |= (1 << 25);
	*pRCC_CFGR |= (1 << 26);

	//3. Config PIN PA8 is Alternate function mode
	*pGPIOA_MODER &= ~(3 << 16);
	*pGPIOA_MODER |= (2 << 16);

	uint32_t *pGPIOA_AFHR = (uint32_t*)GPIOA_AFHR;
	//4.C Config the alternate function register to set the mode 0 for PA8
	*pGPIOA_AFHR &= ~(0xf << 0);

    /* Loop forever */
	for(;;);
}
